### ISSUE TITLE
Régler l'heure docker host

### ISSUE THREAD

**Issue by Pidgeey** [orykami/hive#11]
Mauvais heure renseignée lors d'une entrée en BDD.

Exemple:
- Heure réelle -> 10:00
- Heure inscrite en BDD -> 8:00

**Comment by orykami** [comment]
@Pidgeey J'ai ajouté une variable d'environnement APP_TIMEZONE dans le fichier d'environnement, qui permet de définir sur quel fuseau horaire tourne l'ensemble des containers de hive. La prochaine release va intégrer cette feature
