### ISSUE TITLE
Pouvoir accéder au domaine depuis l'extérieur

### ISSUE THREAD

**Issue by helitik** [orykami/hive#3]
Pour le moment, on peut accéder depuis l'extérieur en ajoutant dans le fichier /etc/hosts :
192.168.{ip_machine} api.hive.dev.local

https://api.hive.dev.local:8081/ fonctionne avec une exception de sécurité.

Possibilité d'améliorer ce comportement ?

**Comment by magsout** [comment]
Une piste peut-être https://github.com/FiloSottile/mkcert

**Comment by orykami** [comment]
Fixé dans le tag 0.4.0
